backend:
  name: gitlab
  branch: master
  repo: rm82dc/guacamayadev

media_folder: 'src/assets/images/uploads'
public_folder: 'assets/images/uploads'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'blog'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: false }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          required: false,
        }
      - {
          label: 'Publish',
          name: 'publish',
          widget: 'boolean',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }