backend:
  name: gitlab
  branch: master
  repo: rm82dc/guacamayadev

media_folder: 'src/assets/images/uploads'
public_folder: 'assets/images/uploads'

collections:
#  - name: 'blog'
#    label: 'Blog'
#    folder: 'blog'
#    create: true
#    fields:
#      - { label: 'Title', name: 'title', widget: 'string', required: false }
#      - {
#          label: 'Description',
#          name: 'description',
#          widget: 'text',
#          required: false,
#        }
#      - {
#          label: 'Publish',
#          name: 'publish',
#          widget: 'boolean',
#          required: false,
#        }
#      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'blog/home.md'
        label: 'Landing Page'
        name: 'home'
        fields:
          - {label: Slug, name: name, widget: string}
          - {label: Title in Menu, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Order in Menu, name: order, widget: number, valueType: int}
          - {label: Publish, name: publish, widget: boolean, default: false}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Sponsors, name: sponsors, widget: list, fields: [{label: Name, name: sponsor_name, widget: string}, {label: Image, name: sponsor_image, widget: image}]}
          - {label: Twitter Feeds, name: twitter_feeds, widget: object, fields: [{label: Section Name, name: section_name, widget: string}, {label: Link, name: link, widget: string}]}
          - {label: Youtube Episodes, name: episodes, widget: object, fields: [{label: Section Name, name: section_name, widget: string}, {label: Channel url, name: channel, widget: string}]}